Small addition for pure black-body atmospheres
astropy/SPISEA pull request #59
Opened 2022-01-12 19:54 UTC by abhimat

Added new function, `atmospheres.get_bb_atmosphere()`, for returning black-body atmosphere. Modified `test_models.test_atmosphere_model()` to test the new black-body atmosphere code.

2022-01-19 17:13 UTC, jluastro requested changes

2022-01-19 17:13 UTC, jluastro commented on spisea/atmospheres.py
> +    bbspec *= (1000 * 3.08e18 / 6.957e10)**2
Can you add a comment about what these constants are and where they came from?

2022-01-19 17:13 UTC, jluastro commented on spisea/atmospheres.py
> +    bbspec *= (1000 * 3.08e18 / 6.957e10)**2
Matt's comment... you will likely need the same inputs as the other atmosphere models (add metallicity, gravity, rebin etc... just ignore these.

2022-01-20 07:51 UTC, abhimat commented
Thanks for the suggestions! I've incorporated these changes into the [latest commit](https://github.com/astropy/SPISEA/commit/04f087e)

2022-01-20 19:50 UTC, mwhosek approved these changes

2022-01-24 18:03 UTC, merged